[package]
name = "rust-risk"
version = "0.2.6-rc3"
authors = ["Mautamu <mautamu@protonmail.com>"]
edition = "2021"

[dependencies]
base64 = {version = "0.13.0", optional=true}
captcha = {version = "0.0.8", optional=true}
chrono = {version = "0.4.19", features = ["serde"]}
git-version = "0.3.4"
time = "0.2.27"
diesel = { version = "1.4.8", features = ["postgres", "r2d2", "uuid", "chrono", "numeric", "serde_json"] }
diesel-citext = {git = "https://github.com/mautamu/diesel-citext"}
#diesel-citext = {git = "https://github.com/afonso360/diesel-citext"}
hyper = { version = "0.14.16", features = ["full"] }
image = {version = "0.24.1", optional=true}
nsvg = {version = "0.5.1", optional=true}
jsonwebtoken = "8.0.1"
rand = {version = "0.8", features = ["std"]}
rand_chacha="0.3"
reqwest = { version = "0.11.8", default-features = false, features = ["json", "rustls-tls"] }
rocket = {version = "0.5.0-rc.1", features = ["secrets", "json"] }
#rocket-governor = {package ="rocket-governor", git = "https://github.com/CollegeFootballRisk/rocket-governor", rev = "8668f86", features = ["limit_info"], optional = true}
#rocket-governor-cloudflare = {package ="rocket-governor", git = "https://github.com/CollegeFootballRisk/rocket-governor", rev = "db2787f", features = ["limit_info", "cloudflare"], optional = true}
rocket_sync_db_pools = {version = "0.1.0-rc.1", features=["diesel_postgres_pool"]}
rocket_oauth2 = {version = "0.5.0-rc.1", features = ["hyper_rustls_adapter"]}
okapi = {package="okapi", git = "https://github.com/GREsau/okapi", rev = "b5b0a89b273f04342d1cb615fef0642beef33cef" }
rocket_okapi = { git = "https://github.com/GREsau/okapi", rev = "b5b0a89b273f04342d1cb615fef0642beef33cef",features = ["swagger"] }
schemars = { version = "0.8", features = ["preserve_order"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
thiserror = "1.0"
toml="0.5.8"
urlencoding = "2.1.0"
#xdg = "2.2.0" # will use this to move files from build to /var/www at preference

[features]
chaos = []
default = ["risk_reddit"]
#risk_cloudflare = ["rocket-governor-cloudflare"]
#risk_no_cloudflare = ["rocket-governor"]
risk_discord = []
risk_groupme = []
risk_image = ["image", "nsvg"]
risk_reddit = []
risk_security = []
risk_captcha = ["captcha", "base64"]

[[bin]]
name = "rrserver"
path = "src/server.rs"

[[bin]]
name = "rrringmaster"
path = "src/ringmaster.rs"
