openapi: 3.0.1
info:
 title: untitled API
 version: '549'
paths:
 /api/me:
  get:
   operationId: request_wEA23owSo1
   summary: Current User
   responses:
    '200':
     content:
      application/json:
       schema:
        type: object
        required:
         - active_team
         - name
         - platform
         - ratings
         - stats
         - team
         - turns
        properties:
         name:
          type: string
         stats:
          type: object
          required:
           - awards
           - gameTurns
           - mvps
           - streak
           - totalTurns
          properties:
           streak:
            type: number
           awards:
            type: number
           gameTurns:
            type: number
           totalTurns:
            type: number
           mvps:
            type: number
         active_team:
          type: object
          required:
           - colors
           - name
          properties:
           colors:
            type: object
            required:
             - primary
             - secondary
            properties:
             primary:
              type: string
             secondary:
              type: string
           name:
            type: string
         team:
          type: object
          required:
           - colors
           - name
          properties:
           colors:
            type: object
            required:
             - primary
             - secondary
            properties:
             primary:
              type: string
             secondary:
              type: string
           name:
            type: string
         ratings:
          type: object
          required:
           - awards
           - gameTurns
           - mvps
           - overall
           - streak
           - totalTurns
          properties:
           streak:
            type: number
           awards:
            type: number
           gameTurns:
            type: number
           totalTurns:
            type: number
           mvps:
            type: number
           overall:
            type: number
         turns:
          type: array
          items:
           type: object
           required:
            - day
            - mvp
            - season
            - stars
            - team
            - territory
           properties:
            stars:
             type: number
            mvp:
             type: boolean
            season:
             type: number
            territory:
             type: string
            team:
             type: string
            day:
             type: number
         platform:
          type: string
     description: ''
    '401':
     content:
      text/html:
       schema:
        type: string
     description: ''
  parameters: []
 /api/heat:
  get:
   operationId: request_YVDqIdZ3yG
   summary: Heat Map
   description: 'Optional: ?season, ?day'
   responses:
    '200':
     content:
      application/json:
       schema:
        type: array
        items:
         type: object
         required:
          - players
          - power
          - territory
          - winner
         properties:
          players:
           type: number
          power:
           type: number
          territory:
           type: string
          winner:
           type: string
     description: ''
  parameters: []
 /api/players:
  get:
   operationId: request_MRsBb07TBI
   summary: Player Information
   description: 'Optional: ?team'
   responses:
    '200':
     content:
      application/json:
       schema:
        type: array
        items:
         type: object
         required:
          - lastTurn
          - mvps
          - player
          - team
          - turnsPlayed
         properties:
          player:
           type: string
          lastTurn:
           type: object
           required:
            - day
            - season
            - stars
           properties:
            day:
             type: number
            season:
             type: number
            stars:
             type: number
          team:
           type: string
          mvps:
           type: number
          turnsPlayed:
           type: number
     description: ''
  parameters: []
 /api/territory/turn:
  get:
   operationId: request_OKKOjCoK29
   summary: Territory Turn Ownership and Moves
   description: 'Required: ?team, ?season, ?day'
   responses:
    '200':
     content:
      application/json:
       schema:
        type: object
        required:
         - occupier
         - players
         - teams
         - winner
        properties:
         occupier:
          type: string
         players:
          type: array
          items:
           type: object
           required:
            - multiplier
            - mvp
            - player
            - power
            - stars
            - team
            - weight
           properties:
            weight:
             type: number
            stars:
             type: number
            mvp:
             type: boolean
            player:
             type: string
            multiplier:
             type: number
            team:
             type: string
            power:
             type: number
         teams:
          type: array
          items:
           type: object
           required:
            - breakdown
            - chance
            - color
            - players
            - power
            - secondaryColor
            - team
           properties:
            players:
             type: number
            breakdown:
             type: object
             required:
              - fives
              - fours
              - ones
              - threes
              - twos
             properties:
              twos:
               type: number
              fives:
               type: number
              threes:
               type: number
              ones:
               type: number
              fours:
               type: number
            color:
             type: string
            secondaryColor:
             type: string
            chance:
             type: number
            team:
             type: string
            power:
             type: number
         winner:
          type: string
     description: ''
  parameters: []
 /api/territories:
  get:
   operationId: request_eNqL7n91Xc
   summary: Territory Owners
   description: 'Optional: ?day, ?season'
   responses:
    '200':
     content:
      application/json:
       schema:
        type: array
        items:
         type: object
         required:
          - id
          - name
          - neighbors
          - owner
         properties:
          id:
           type: number
          name:
           type: string
          neighbors:
           type: array
           items:
            type: object
            required:
             - id
             - name
             - owner
             - shortName
            properties:
             id:
              type: number
             name:
              type: string
             owner:
              type: string
             shortName:
              type: string
          owner:
           type: string
     description: ''
  parameters: []
 /api/stats/team/history:
  get:
   operationId: request_ccjDkxwhdT
   summary: Team Historical Stats
   responses:
    '200':
     content:
      application/json:
       schema:
        type: array
        items:
         type: object
         required:
          - day
          - effectivePower
          - players
          - season
          - sequence
          - starPower
          - starbreakdown
          - territories
         properties:
          players:
           type: number
          starPower: {}
          effectivePower:
           type: number
          season:
           type: number
          sequence:
           type: number
          starbreakdown:
           type: object
           required:
            - fives
            - fours
            - ones
            - threes
            - twos
           properties:
            twos:
             type: number
            fives:
             type: number
            threes:
             type: number
            ones:
             type: number
            fours:
             type: number
          territories:
           type: number
          day:
           type: number
     description: ''
  parameters: []
 /api/turns/all:
  get:
   operationId: request_Ss6UKXlDUP
   summary: Turn Information
   responses:
    '200':
     content:
      application/json:
       schema:
        type: array
        items:
         type: object
         required:
          - active
          - complete
          - day
          - finale
          - id
          - rollTime
          - season
         properties:
          season:
           type: number
          id:
           type: number
          complete:
           type: boolean
          finale:
           type: boolean
          rollTime: {}
          day:
           type: number
          active:
           type: boolean
     description: ''
  parameters: []
 /api/player:
  get:
   operationId: request_Gpry4lYabu
   summary: Player Information
   description: 'Required: ?player'
   responses:
    '200':
     content:
      application/json:
       schema:
        type: object
        required:
         - active_team
         - name
         - platform
         - ratings
         - stats
         - team
         - turns
        properties:
         name:
          type: string
         stats:
          type: object
          required:
           - awards
           - gameTurns
           - mvps
           - streak
           - totalTurns
          properties:
           streak:
            type: number
           awards:
            type: number
           gameTurns:
            type: number
           totalTurns:
            type: number
           mvps:
            type: number
         active_team:
          type: object
          required:
           - colors
           - name
          properties:
           colors:
            type: object
            required:
             - primary
             - secondary
            properties:
             primary:
              type: string
             secondary:
              type: string
           name:
            type: string
         team:
          type: object
          required:
           - colors
           - name
          properties:
           colors:
            type: object
            required:
             - primary
             - secondary
            properties:
             primary:
              type: string
             secondary:
              type: string
           name:
            type: string
         ratings:
          type: object
          required:
           - awards
           - gameTurns
           - mvps
           - overall
           - streak
           - totalTurns
          properties:
           streak:
            type: number
           awards:
            type: number
           gameTurns:
            type: number
           totalTurns:
            type: number
           mvps:
            type: number
           overall:
            type: number
         turns:
          type: array
          items:
           type: object
           required:
            - day
            - mvp
            - season
            - stars
            - team
            - territory
           properties:
            stars:
             type: number
            mvp:
             type: boolean
            season:
             type: number
            territory:
             type: string
            team:
             type: string
            day:
             type: number
         platform:
          type: string
     description: ''
  parameters: []
 /api/teams:
  get:
   operationId: request_wwDgfYmMS2
   summary: Current Teams
   description: 'Optional: ?season'
   responses:
    '200':
     content:
      application/json:
       schema:
        type: array
        items:
         type: object
         required:
          - colors
          - id
          - logo
          - name
          - seasons
         properties:
          name:
           type: string
          colors:
           type: object
           required:
            - primary
            - secondary
           properties:
            primary:
             type: string
            secondary:
             type: string
          logo:
           type: string
          id:
           type: number
          seasons:
           type: array
           items:
            type: number
     description: ''
  parameters: []
 /api/stats/leaderboard:
  get:
   operationId: request_WQAkOU0Usg
   summary: Leaderboard Information
   description: 'Optional: ?season, ?day'
   responses:
    '200':
     content:
      application/json:
       schema:
        type: array
        items:
         type: object
         required:
          - efficiency
          - logo
          - mercCount
          - name
          - playerCount
          - rank
          - starPower
          - territoryCount
         properties:
          efficiency:
           type: number
          name:
           type: string
          rank:
           type: number
          starPower:
           type: number
          logo:
           type: string
          playerCount:
           type: number
          territoryCount:
           type: number
          mercCount:
           type: number
     description: ''
  parameters: []
 /api/team/odds:
  get:
   operationId: request_VzYC9ozeod
   summary: Team Odds
   description: 'Required: ?team, ?season, ?day'
   responses:
    '200':
     content:
      application/json:
       schema:
        type: array
        items:
         type: object
         required:
          - chance
          - mvp
          - owner
          - players
          - starBreakdown
          - teamPower
          - territory
          - territoryPower
          - winner
         properties:
          winner:
           type: string
          players:
           type: number
          mvp: {}
          starBreakdown:
           type: object
           required:
            - fives
            - fours
            - ones
            - threes
            - twos
           properties:
            twos:
             type: number
            fives:
             type: number
            threes:
             type: number
            ones:
             type: number
            fours:
             type: number
          territory:
           type: string
          chance:
           type: number
          territoryPower:
           type: number
          teamPower:
           type: number
          owner:
           type: string
     description: ''
    '400':
     content:
      text/html:
       schema:
        type: string
     description: ''
  parameters: []
 /api/territory/history:
  get:
   operationId: request_wrYQXi4Jkg
   summary: Territory History
   responses:
    '200':
     content:
      application/json:
       schema:
        type: array
        items:
         type: object
         required:
          - day
          - owner
          - season
          - territory
         properties:
          day:
           type: number
          owner:
           type: string
          season:
           type: number
          territory:
           type: string
     description: ''
  parameters: []
 /api/stats/team:
  get:
   operationId: request_6SkgYpN5Tp
   summary: Team Strength
   description: 'Required: ?team, Optional: &day={day}&season={season}'
   responses:
    '200':
     content:
      application/json:
       schema:
        type: object
        required:
         - mercs
         - players
         - stars
         - team
         - territories
        properties:
         players:
          type: number
         stars:
          type: number
         mercs:
          type: number
         team:
          type: string
         territories:
          type: number
     description: ''
  parameters: []
 /api/turns:
  get:
   operationId: request_UsCACESCxo
   summary: Turn Information
   responses:
    '200':
     content:
      application/json:
       schema:
        type: array
        items:
         type: object
         required:
          - active
          - complete
          - day
          - finale
          - id
          - rollTime
          - season
         properties:
          season:
           type: number
          id:
           type: number
          complete:
           type: boolean
          finale:
           type: boolean
          rollTime: {}
          day:
           type: number
          active:
           type: boolean
     description: ''
  parameters: []
components:
 schemas: {}
