[package]
name = "rr_proc_macros"
version = "0.0.0"
authors = ["Mautamu <mautam@usa.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1", features = ["nightly"] }
quote = "1"
syn = { version = "2.0.17", features = ["full", "parsing", "fold"] }
