begin transaction;
insert into territories(id, name, region) values (27, 'Atlanta', 5);
insert into territories(id, name, region) values (28, 'Denver', 5);
insert into territories(id, name, region) values (29, 'Des Moines',6);
insert into territories(id, name, region) values (30, 'Lansing',6);
insert into territories(id, name, region) values (31, 'Lincoln',6);
insert into territories(id, name, region) values (32, 'Little Rock',5);
insert into territories(id, name, region) values (33, 'Oklahoma City',6);
insert into territories(id, name, region) values (34, 'Sacramento',5);
insert into territories(id, name, region) values (35, 'Saint Paul', 5);
insert into territories(id, name, region) values (36, 'Topeka',6);

update territories set region = 1 where name in ('Alpine', 'Austin', 'Amarillo', 'Uvalde', 'College Station', 'Lubbock');
update territories set region = 2 where name in ('Abilene', 'Turkey','San Antonio', 'Tyler', 'Pampa', 'San Angelo', 'Ozona');
update territories set region = 3 where name in ('Nacogdoches','Odessa','Laredo', 'Houston','Victoria', 'Waco');
update territories set region = 4 where name in ('Fort Worth', 'El Paso', 'Denton', 'Corpus Christi', 'Dallas', 'El Campo', 'Wichita Falls');



insert into territory_ownership(territory_id, owner_id, day, season, previous_owner_id, random_number) values (27, 17, 20, 2, 7, 0);
insert into territory_ownership(territory_id, owner_id, day, season, previous_owner_id, random_number) values (28, 19, 20, 2, 7, 0);
insert into territory_ownership(territory_id, owner_id, day, season, previous_owner_id, random_number) values (29, 20, 20, 2, 7, 0);
insert into territory_ownership(territory_id, owner_id, day, season, previous_owner_id, random_number) values (30, 8, 20, 2, 7, 0);
insert into territory_ownership(territory_id, owner_id, day, season, previous_owner_id, random_number) values (31, 9, 20, 2, 7, 0);
insert into territory_ownership(territory_id, owner_id, day, season, previous_owner_id, random_number) values (32, 10, 20, 2, 7, 0);
insert into territory_ownership(territory_id, owner_id, day, season, previous_owner_id, random_number) values (33, 13, 20, 2, 7, 0);
insert into territory_ownership(territory_id, owner_id, day, season, previous_owner_id, random_number) values (34, 14, 20, 2, 7, 0);
insert into territory_ownership(territory_id, owner_id, day, season, previous_owner_id, random_number) values (35, 15, 20, 2, 7, 0);
insert into territory_ownership(territory_id, owner_id, day, season, previous_owner_id, random_number) values (36, 21, 20, 2, 7, 0);

delete from territory_adjacency;
insert into territory_adjacency(territory_id, adjacent_id) values (1,1);	insert into territory_adjacency(territory_id, adjacent_id) values (1,2);	insert into territory_adjacency(territory_id, adjacent_id) values (1,4);	insert into territory_adjacency(territory_id, adjacent_id) values (1,22);	insert into territory_adjacency(territory_id, adjacent_id) values (1,18);	insert into territory_adjacency(territory_id, adjacent_id) values (1,21);			
insert into territory_adjacency(territory_id, adjacent_id) values (2,2);	insert into territory_adjacency(territory_id, adjacent_id) values (2,3);	insert into territory_adjacency(territory_id, adjacent_id) values (2,4);	insert into territory_adjacency(territory_id, adjacent_id) values (2,1);					
insert into territory_adjacency(territory_id, adjacent_id) values (3,3);	insert into territory_adjacency(territory_id, adjacent_id) values (3,5);	insert into territory_adjacency(territory_id, adjacent_id) values (3,23);	insert into territory_adjacency(territory_id, adjacent_id) values (3,4);	insert into territory_adjacency(territory_id, adjacent_id) values (3,2);				
insert into territory_adjacency(territory_id, adjacent_id) values (4,4);	insert into territory_adjacency(territory_id, adjacent_id) values (4,23);	insert into territory_adjacency(territory_id, adjacent_id) values (4,3);	insert into territory_adjacency(territory_id, adjacent_id) values (4,2);	insert into territory_adjacency(territory_id, adjacent_id) values (4,1);	insert into territory_adjacency(territory_id, adjacent_id) values (4,22);			
insert into territory_adjacency(territory_id, adjacent_id) values (5,5);	insert into territory_adjacency(territory_id, adjacent_id) values (5,6);	insert into territory_adjacency(territory_id, adjacent_id) values (5,8);	insert into territory_adjacency(territory_id, adjacent_id) values (5,11);	insert into territory_adjacency(territory_id, adjacent_id) values (5,14);	insert into territory_adjacency(territory_id, adjacent_id) values (5,23);	insert into territory_adjacency(territory_id, adjacent_id) values (5,3);		
insert into territory_adjacency(territory_id, adjacent_id) values (6,6);	insert into territory_adjacency(territory_id, adjacent_id) values (6,7);	insert into territory_adjacency(territory_id, adjacent_id) values (6,8);	insert into territory_adjacency(territory_id, adjacent_id) values (6,5);					
insert into territory_adjacency(territory_id, adjacent_id) values (7,7);	insert into territory_adjacency(territory_id, adjacent_id) values (7,26);	insert into territory_adjacency(territory_id, adjacent_id) values (7,9);	insert into territory_adjacency(territory_id, adjacent_id) values (7,8);	insert into territory_adjacency(territory_id, adjacent_id) values (7,6);				
insert into territory_adjacency(territory_id, adjacent_id) values (8,8);	insert into territory_adjacency(territory_id, adjacent_id) values (8,7);	insert into territory_adjacency(territory_id, adjacent_id) values (8,6);	insert into territory_adjacency(territory_id, adjacent_id) values (8,5);	insert into territory_adjacency(territory_id, adjacent_id) values (8,9);	insert into territory_adjacency(territory_id, adjacent_id) values (8,10);	insert into territory_adjacency(territory_id, adjacent_id) values (8,11);		
insert into territory_adjacency(territory_id, adjacent_id) values (9,9);	insert into territory_adjacency(territory_id, adjacent_id) values (9,26);	insert into territory_adjacency(territory_id, adjacent_id) values (9,7);	insert into territory_adjacency(territory_id, adjacent_id) values (9,25);	insert into territory_adjacency(territory_id, adjacent_id) values (9,10);	insert into territory_adjacency(territory_id, adjacent_id) values (9,8);			
insert into territory_adjacency(territory_id, adjacent_id) values (10,10);	insert into territory_adjacency(territory_id, adjacent_id) values (10,24);	insert into territory_adjacency(territory_id, adjacent_id) values (10,25);	insert into territory_adjacency(territory_id, adjacent_id) values (10,9);	insert into territory_adjacency(territory_id, adjacent_id) values (10,8);	insert into territory_adjacency(territory_id, adjacent_id) values (10,11);	insert into territory_adjacency(territory_id, adjacent_id) values (10,12);		
insert into territory_adjacency(territory_id, adjacent_id) values (11,11);	insert into territory_adjacency(territory_id, adjacent_id) values (11,5);	insert into territory_adjacency(territory_id, adjacent_id) values (11,8);	insert into territory_adjacency(territory_id, adjacent_id) values (11,10);	insert into territory_adjacency(territory_id, adjacent_id) values (11,12);	insert into territory_adjacency(territory_id, adjacent_id) values (11,14);			
insert into territory_adjacency(territory_id, adjacent_id) values (12,12);	insert into territory_adjacency(territory_id, adjacent_id) values (12,13);	insert into territory_adjacency(territory_id, adjacent_id) values (12,24);	insert into territory_adjacency(territory_id, adjacent_id) values (12,11);	insert into territory_adjacency(territory_id, adjacent_id) values (12,14);	insert into territory_adjacency(territory_id, adjacent_id) values (12,10);			
insert into territory_adjacency(territory_id, adjacent_id) values (13,13);	insert into territory_adjacency(territory_id, adjacent_id) values (13,15);	insert into territory_adjacency(territory_id, adjacent_id) values (13,14);	insert into territory_adjacency(territory_id, adjacent_id) values (13,12);	insert into territory_adjacency(territory_id, adjacent_id) values (13,24);				
insert into territory_adjacency(territory_id, adjacent_id) values (14,14);	insert into territory_adjacency(territory_id, adjacent_id) values (14,5);	insert into territory_adjacency(territory_id, adjacent_id) values (14,23);	insert into territory_adjacency(territory_id, adjacent_id) values (14,15);	insert into territory_adjacency(territory_id, adjacent_id) values (14,13);	insert into territory_adjacency(territory_id, adjacent_id) values (14,11);	insert into territory_adjacency(territory_id, adjacent_id) values (14,12);	insert into territory_adjacency(territory_id, adjacent_id) values (14,16);	insert into territory_adjacency(territory_id, adjacent_id) values (14,22);
insert into territory_adjacency(territory_id, adjacent_id) values (15,15);	insert into territory_adjacency(territory_id, adjacent_id) values (15,17);	insert into territory_adjacency(territory_id, adjacent_id) values (15,16);	insert into territory_adjacency(territory_id, adjacent_id) values (15,14);	insert into territory_adjacency(territory_id, adjacent_id) values (15,13);				
insert into territory_adjacency(territory_id, adjacent_id) values (16,16);	insert into territory_adjacency(territory_id, adjacent_id) values (16,23);	insert into territory_adjacency(territory_id, adjacent_id) values (16,17);	insert into territory_adjacency(territory_id, adjacent_id) values (16,15);	insert into territory_adjacency(territory_id, adjacent_id) values (16,14);	insert into territory_adjacency(territory_id, adjacent_id) values (16,22);	insert into territory_adjacency(territory_id, adjacent_id) values (16,19);		
insert into territory_adjacency(territory_id, adjacent_id) values (17,17);	insert into territory_adjacency(territory_id, adjacent_id) values (17,18);	insert into territory_adjacency(territory_id, adjacent_id) values (17,19);	insert into territory_adjacency(territory_id, adjacent_id) values (17,16);	insert into territory_adjacency(territory_id, adjacent_id) values (17,15);				
insert into territory_adjacency(territory_id, adjacent_id) values (18,18);	insert into territory_adjacency(territory_id, adjacent_id) values (18,1);	insert into territory_adjacency(territory_id, adjacent_id) values (18,21);	insert into territory_adjacency(territory_id, adjacent_id) values (18,20);	insert into territory_adjacency(territory_id, adjacent_id) values (18,17);	insert into territory_adjacency(territory_id, adjacent_id) values (18,19);	insert into territory_adjacency(territory_id, adjacent_id) values (18,22);		
insert into territory_adjacency(territory_id, adjacent_id) values (19,19);	insert into territory_adjacency(territory_id, adjacent_id) values (19,18);	insert into territory_adjacency(territory_id, adjacent_id) values (19,17);	insert into territory_adjacency(territory_id, adjacent_id) values (19,16);	insert into territory_adjacency(territory_id, adjacent_id) values (19,22);				
insert into territory_adjacency(territory_id, adjacent_id) values (20,20);	insert into territory_adjacency(territory_id, adjacent_id) values (20,21);	insert into territory_adjacency(territory_id, adjacent_id) values (20,18);						
insert into territory_adjacency(territory_id, adjacent_id) values (21,21);	insert into territory_adjacency(territory_id, adjacent_id) values (21,1);	insert into territory_adjacency(territory_id, adjacent_id) values (21,22);	insert into territory_adjacency(territory_id, adjacent_id) values (21,18);	insert into territory_adjacency(territory_id, adjacent_id) values (21,20);				
insert into territory_adjacency(territory_id, adjacent_id) values (22,22);	insert into territory_adjacency(territory_id, adjacent_id) values (22,23);	insert into territory_adjacency(territory_id, adjacent_id) values (22,4);	insert into territory_adjacency(territory_id, adjacent_id) values (22,1);	insert into territory_adjacency(territory_id, adjacent_id) values (22,21);	insert into territory_adjacency(territory_id, adjacent_id) values (22,18);	insert into territory_adjacency(territory_id, adjacent_id) values (22,14);	insert into territory_adjacency(territory_id, adjacent_id) values (22,16);	insert into territory_adjacency(territory_id, adjacent_id) values (22,19);
insert into territory_adjacency(territory_id, adjacent_id) values (23,23);	insert into territory_adjacency(territory_id, adjacent_id) values (23,5);	insert into territory_adjacency(territory_id, adjacent_id) values (23,14);	insert into territory_adjacency(territory_id, adjacent_id) values (23,16);	insert into territory_adjacency(territory_id, adjacent_id) values (23,22);	insert into territory_adjacency(territory_id, adjacent_id) values (23,4);	insert into territory_adjacency(territory_id, adjacent_id) values (23,3);		
insert into territory_adjacency(territory_id, adjacent_id) values (24,24);	insert into territory_adjacency(territory_id, adjacent_id) values (24,13);	insert into territory_adjacency(territory_id, adjacent_id) values (24,12);	insert into territory_adjacency(territory_id, adjacent_id) values (24,10);	insert into territory_adjacency(territory_id, adjacent_id) values (24,25);				
insert into territory_adjacency(territory_id, adjacent_id) values (25,25);	insert into territory_adjacency(territory_id, adjacent_id) values (25,24);	insert into territory_adjacency(territory_id, adjacent_id) values (25,10);	insert into territory_adjacency(territory_id, adjacent_id) values (25,9);					
insert into territory_adjacency(territory_id, adjacent_id) values (26,26);	insert into territory_adjacency(territory_id, adjacent_id) values (26,9);	insert into territory_adjacency(territory_id, adjacent_id) values (26,7);						
insert into territory_adjacency(territory_id, adjacent_id) values (27,27);	insert into territory_adjacency(territory_id, adjacent_id) values (27,35);	insert into territory_adjacency(territory_id, adjacent_id) values (27,34);	insert into territory_adjacency(territory_id, adjacent_id) values (27,32);				
insert into territory_adjacency(territory_id, adjacent_id) values (28,28);	insert into territory_adjacency(territory_id, adjacent_id) values (28,34);	insert into territory_adjacency(territory_id, adjacent_id) values (28,35);					
insert into territory_adjacency(territory_id, adjacent_id) values (29,29);	insert into territory_adjacency(territory_id, adjacent_id) values (29,33);	insert into territory_adjacency(territory_id, adjacent_id) values (29,30);	insert into territory_adjacency(territory_id, adjacent_id) values (29,36);				
insert into territory_adjacency(territory_id, adjacent_id) values (30,30);	insert into territory_adjacency(territory_id, adjacent_id) values (30,32);	insert into territory_adjacency(territory_id, adjacent_id) values (30,33);	insert into territory_adjacency(territory_id, adjacent_id) values (30,29);	insert into territory_adjacency(territory_id, adjacent_id) values (30,36);	insert into territory_adjacency(territory_id, adjacent_id) values (30,31);		
insert into territory_adjacency(territory_id, adjacent_id) values (31,31);	insert into territory_adjacency(territory_id, adjacent_id) values (31,30);	insert into territory_adjacency(territory_id, adjacent_id) values (31,36);					
insert into territory_adjacency(territory_id, adjacent_id) values (32,32);	insert into territory_adjacency(territory_id, adjacent_id) values (32,27);	insert into territory_adjacency(territory_id, adjacent_id) values (32,34);	insert into territory_adjacency(territory_id, adjacent_id) values (32,33);	insert into territory_adjacency(territory_id, adjacent_id) values (32,30);			
insert into territory_adjacency(territory_id, adjacent_id) values (33,33);	insert into territory_adjacency(territory_id, adjacent_id) values (33,32);	insert into territory_adjacency(territory_id, adjacent_id) values (33,34);	insert into territory_adjacency(territory_id, adjacent_id) values (33,30);	insert into territory_adjacency(territory_id, adjacent_id) values (33,29);			
insert into territory_adjacency(territory_id, adjacent_id) values (34,34);	insert into territory_adjacency(territory_id, adjacent_id) values (34,28);	insert into territory_adjacency(territory_id, adjacent_id) values (34,35);	insert into territory_adjacency(territory_id, adjacent_id) values (34,27);	insert into territory_adjacency(territory_id, adjacent_id) values (34,32);	insert into territory_adjacency(territory_id, adjacent_id) values (34,33);		
insert into territory_adjacency(territory_id, adjacent_id) values (35,35);	insert into territory_adjacency(territory_id, adjacent_id) values (35,28);	insert into territory_adjacency(territory_id, adjacent_id) values (35,27);	insert into territory_adjacency(territory_id, adjacent_id) values (35,34);				
insert into territory_adjacency(territory_id, adjacent_id) values (36,36);	insert into territory_adjacency(territory_id, adjacent_id) values (36,30);	insert into territory_adjacency(territory_id, adjacent_id) values (36,29);	insert into territory_adjacency(territory_id, adjacent_id) values (36,31);				


insert into stats(sequence, season, day, team, rank, territorycount, playercount, merccount, starpower, efficiency, effectivepower, ones,twos, threes,fours,fives) values (14, 2, 20, 8, 6, 1, 1, 0,0,0,0,0,0,0,0,0);
insert into stats(sequence, season, day, team, rank, territorycount, playercount, merccount, starpower, efficiency, effectivepower, ones,twos, threes,fours,fives) values (14, 2, 20, 9, 6, 1, 1, 0,0,0,0,0,0,0,0,0);
insert into stats(sequence, season, day, team, rank, territorycount, playercount, merccount, starpower, efficiency, effectivepower, ones,twos, threes,fours,fives) values (14, 2, 20, 10, 6, 1, 1, 0,0,0,0,0,0,0,0,0);
insert into stats(sequence, season, day, team, rank, territorycount, playercount, merccount, starpower, efficiency, effectivepower, ones,twos, threes,fours,fives) values (14, 2, 20, 13, 6, 2, 1, 0,0,0,0,0,0,0,0,0);
insert into stats(sequence, season, day, team, rank, territorycount, playercount, merccount, starpower, efficiency, effectivepower, ones,twos, threes,fours,fives) values (14, 2, 20, 14, 6, 1, 1, 0,0,0,0,0,0,0,0,0);
insert into stats(sequence, season, day, team, rank, territorycount, playercount, merccount, starpower, efficiency, effectivepower, ones,twos, threes,fours,fives) values (14, 2, 20, 15, 6, 1, 1, 0,0,0,0,0,0,0,0,0);
insert into stats(sequence, season, day, team, rank, territorycount, playercount, merccount, starpower, efficiency, effectivepower, ones,twos, threes,fours,fives) values (14, 2, 20, 17, 6, 1, 1, 0,0,0,0,0,0,0,0,0);
insert into stats(sequence, season, day, team, rank, territorycount, playercount, merccount, starpower, efficiency, effectivepower, ones,twos, threes,fours,fives) values (14, 2, 20, 19, 6, 1, 1, 0,0,0,0,0,0,0,0,0);
insert into stats(sequence, season, day, team, rank, territorycount, playercount, merccount, starpower, efficiency, effectivepower, ones,twos, threes,fours,fives) values (14, 2, 20, 20, 6, 1, 1, 0,0,0,0,0,0,0,0,0);
insert into stats(sequence, season, day, team, rank, territorycount, playercount, merccount, starpower, efficiency, effectivepower, ones,twos, threes,fours,fives) values (14, 2, 20, 21, 6, 1, 1, 0,0,0,0,0,0,0,0,0);

